### PR TITLE
Add new publiccode.schema.json

### PR DESCRIPTION
**Pull request by libremente**
## Title
This PR introduces the JSON version of the `publiccode.yml` file in order to have a valid schema to test against for validity.
## Content
A new file is created (now in root).
## Review

- [ ] Ensure your files are written following RST specs (*not MD!*)
- [ ] Italian version
- [ ] English version
- [ ] Ask for review

### CODE REVIEW

**Comment by libremente** [comment]
This looks weird, have to understand how to handle the `description/lang/xxx` thing, since now it's only in italian in the file.

**Comment by ruphy** [comment]
Is this a json-schema or just a ... json copy?

**Comment by libremente** [comment]
> Is this a json-schema or just a ... json copy?

@ruphy We're trying to build an updated (draft 07) JSON schema to be later used for validation purposes (e.g., in the editor). What do you think about it?

**Comment by ruphy** [comment]
I think it's a wonderful idea! We tried it last year and failed to represent the localized strings. If you can, however, build it to the point where it becomes the single file which generates the whole documentation/validator, this would make me very happy!

**Pull request closed without merging**
