### PR TITLE
Add Whistleblowing to the software categories list

### PR DESCRIPTION
**Pull request by evilaliv3**
Reference ticket: https://github.com/publiccodeyml/publiccode.yml/issues/96

### CODE REVIEW

**Comment by bfabio** [comment]
@yaml-9000 minor-change

**Comment by yaml-9000** [comment]
Thanks for your contribution :pray:

This is now marked as a [`minor-change` proposal to the standard](https://github.com/publiccodeyml/publiccode.yml/labels/standard-minor-change),
this means that old versions of `publiccode.yml` will still be valid with this change.

Example of minor changes are additions of new keys or making keys optional.

The Chair will eventually pick up this proposal and start the voting procedure using `@yaml-9000 vote-start`

cc @ruphy @publiccodeyml/steering-committee


<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

**Comment by bfabio** [comment]
Hello @evilaliv3, can you please rebase your PR on main?

**Comment by evilaliv3** [comment]
Absolutely! Thank you for for suppporting this!

**Comment by evilaliv3** [comment]
there you are @bfabio. than you again

cc @ruphy https://github.com/orgs/publiccodeyml/teams/steering-committee

**Comment by evilaliv3** [comment]
@bfabio @ruphy : looking forward to the merge we have anticipated adding the category to our files in order to be apple to re-test it early as available.

Thank you

**Comment by ruphy** [comment]
@yaml-9000 vote-start

**Comment by yaml-9000** [comment]
**Voting is now open on this proposal!**

If you are a member of the [Steering Committee](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md#steering-committee-publiccodeymlsteering-committee) you can now vote!

The polls will stay open for 14 days, until **Wed, 27 Apr 2022 13:03:37 GMT**.
At the end of that period the Chair (@ruphy) will mark the voting period as over using `@yaml-9000 vote-end`

Leave a :+1: (thumbs up) **on this comment** to accept the proposal or a :-1: (thumbs down) to reject it.

cc @publiccodeyml/steering-committee


<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

**Comment by yaml-9000** [comment]
# Vote results

The results of [the vote](https:&#x2F;&#x2F;github.com&#x2F;publiccodeyml&#x2F;publiccode.yml&#x2F;pull&#x2F;97#issuecomment-1098024519) are:

|Vote|Members|Votes count|Percentage|
|-|-|-|-|
|:+1: Approve | @ruphy @bzg   | 2   | 100.0%   |
|:-1: Reject  |  | 0 | - |



**Proposal approved** :+1:

This proposal is now ready to be merged and get released with a new version of the standard.
      

cc @ruphy @publiccodeyml/maintainers


<details>
  <summary><sub>Details<sub></summary>
  <br>
  <p>
    <strong>First round</strong>: unanimity required
  </p>
  <p>
    The following users voted (includes non-members of the steering committee):
  </p>

  - <strong>ruphy</strong> voted :+1:

- <strong>bzg</strong> voted :+1:
</details>


<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

**Comment by evilaliv3** [comment]
Thank you @bfabio 

Will this code run in production starting from tonight?

**Comment by bfabio** [comment]
@evilaliv3 this will take a while to get to production, we need to 

1. Release the new version of the Standard
2. Bring all the changes to publiccode-parser-go and release a new version
3. Make the publiccode crawler use the new version of publiccode-parser-go and deploy it

it'll take a few days

**Comment by evilaliv3** [comment]
@bfabio: I notice that the category has been correctly added to the system but the software page seems to not be able to use it.

https://developers.italia.it/it/software/globaleaks-globaleaks-f22648

Here for example you could see still missing the category whistleblowing.

Would you please check it on which component i should eventually open an issue?

Thank you!

**Comment by bfabio** [comment]
@evilaliv3 that would be https://github.com/italia/developers.italia.it/ material, thanks :raised_hands:

**Pull request merged**
