### PR TITLE
Initialize French translation

### PR DESCRIPTION
**Pull request by nclsppr**
## Content
I decided to start the french translation of your documentation. PublicCode project is something really interesting and I thought it deserved a french translation.
I hope that it will help you to kickstart the french documentation.
It still miss some files and I hope to have time to complete them ! 
Be aware that forks.rst is partially translated. 

## Review

- [X] Ensure your files are written following RST specs (*not MD!*)
- [ ] Italian version
- [ ] English version
- [X] French version
- [ ] Example files 
- [X] Ask for review

### CODE REVIEW

**Comment by libremente** [comment]
Thanks @nclsppr! Your contribution is great! We will try to review it soon and try to help you in order to merge it 👍

**Comment by ruphy** [comment]
I just merged #74 which seems to conflict with this PR. Is there any translation work which should be cherry-picked to master?

**Comment by bzg** [comment]
If @nclsppr does not have the time to check this PR this week, I will have a look at the end of the next week. Thanks!

**Comment by bzg** [comment]
Hi @ruphy, I've looked at the PR and the only conflict with `master` is in `docs/fr/schema.core.rst`.

You can simply merge this PR while discarding changes made to `docs/fr/schema.core.rst` in this PR, since the version of this file in `master` contains translations while the version in this PR is not translated at all.

@nclsppr let me know if I'm missing something.

**Pull request merged**
