### PR TITLE
proposal to add educational-content category

### PR DESCRIPTION
**Pull request by Animtim**
## Title
Proposal to add educational-content category

## Content
This new category would fit better for GCompris.
Added the new category to categories-list.rst in en and it.

## Review

- [x] Ensure your files are written following RST specs (*not MD!*)
- [x] Italian version
- [x] English version
- [ ] Example files 
- [ ] Ask for review

### CODE REVIEW

**Comment by bfabio** [comment]
@yaml-9000 minor-change

**Comment by bfabio** [comment]
Hi @Animtim, can you please rebase your PR on main?

**Comment by yaml-9000** [comment]
Thanks for your contribution :pray:

This is now marked as a [`minor-change` proposal to the standard](https://github.com/publiccodeyml/publiccode.yml/labels/standard-minor-change),
this means that old versions of `publiccode.yml` will still be valid with this change.

Example of minor changes are additions of new keys or making keys optional.

The Chair will eventually pick up this proposal and start the voting procedure using `@yaml-9000 vote-start`

cc @ruphy @publiccodeyml/steering-committee


<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

**Comment by yaml-9000** [comment]
**Voting is now open on this proposal!**

If you are a member of the [Steering Committee](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md#steering-committee-publiccodeymlsteering-committee) you can now vote!

The polls will stay open for 14 days, until **Wed, 27 Apr 2022 13:02:41 GMT**.
At the end of that period the Chair (@ruphy) will mark the voting period as over using `@yaml-9000 vote-end`

Leave a :+1: (thumbs up) **on this comment** to accept the proposal or a :-1: (thumbs down) to reject it.

cc @publiccodeyml/steering-committee


<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

**Comment by ruphy** [comment]
@yaml-9000 vote-end

**Comment by yaml-9000** [comment]
# Vote results

The results of [the vote](https:&#x2F;&#x2F;github.com&#x2F;publiccodeyml&#x2F;publiccode.yml&#x2F;pull&#x2F;88#issuecomment-1098023648) are:

|Vote|Members|Votes count|Percentage|
|-|-|-|-|
|:+1: Approve | @ruphy @bzg   | 2   | 100.0%   |
|:-1: Reject  |  | 0 | - |



**Proposal approved** :+1:

This proposal is now ready to be merged and get released with a new version of the standard.
      

cc @ruphy @publiccodeyml/maintainers


<details>
  <summary><sub>Details<sub></summary>
  <br>
  <p>
    <strong>First round</strong>: unanimity required
  </p>
  <p>
    The following users voted (includes non-members of the steering committee):
  </p>

  - <strong>ruphy</strong> voted :+1:

- <strong>bzg</strong> voted :+1:
</details>


<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

**Pull request merged**
